/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
*/

class Solution {
    public char findTheDifference(String s, String t) {
        int sum = 0;
        for (char element : t.toCharArray())
            sum += element - 'a';

        for (char element : s.toCharArray())
            sum -= element - 'a';

        return (char) ('a' + sum);
    }
}
